Set Shell zsh
Sleep 500ms
Type "./build/server | sed 's/^/\x1b[1;32m[SERVER]\x1b[0m /' &"
Enter
Sleep 500ms
Type "./build/client patata"
Enter
Sleep 700ms
Enter
Sleep 600ms
Type "patata"
Enter
Sleep 200ms
Type "password"
Enter
Sleep 700ms
Enter
Sleep 700ms
Escape
Type "OB"
Sleep 700ms
Enter
Sleep 700ms
Type "fragolino"
Enter
Sleep 200ms
Type "3"
Enter
Sleep 1.5s
Enter
Sleep 1.5s
Escape
Type "OB"
Sleep 700ms
Enter
Sleep 1.5s
Ctrl+D

